### ISSUE TITLE
Check out similar apps/features

### ISSUE THREAD

**Issue by juanmnl** [huridocs/uwazi-design#20]
Find and try apps that have referencing and citing as a feature.

**Comment by juanmnl** [comment]
Summary of the research: https://docs.google.com/spreadsheets/d/1U3CEGqwQyu7NfRnDruewqp8DtdTG82TEk0CnqeIH7Ig/edit?usp=sharing

**Comment by txau** [comment]
Related to this topic, it would be great if we can review how [LEx](https://www.lexisnexis.com) and https://legal.thomsonreuters.com/en/westlaw work.

Also there other open source projects that kind of overlap with Uwazi:

https://www.paclii.org/
http://www.austlii.edu.au/
https://africanlii.org/

**Comment by txau** [comment]
https://www.youtube.com/watch?v=nyUanY9Jq4A

https://www.youtube.com/watch?v=YeeSwh2OC80

**Comment by juanmnl** [comment]
https://themisia.corteidh.or.cr/

**Comment by aphilop** [comment]
Focus more in detail:
LexisNexis - Alex
Zotero - JuanMa

**Comment by aphilop** [comment]
Relevant capabilities of Lexis+/LexisNexis documented in the [Miro board](https://miro.com/app/board/uXjVKu15oZA=/?moveToWidget=3458764599222041051&cot=14).

**Comment by aphilop** [comment]
Zotero review is also in Miro board.
