### ISSUE TITLE
Review existing issues in UWAZI for references

### ISSUE THREAD

**Issue by juanmnl** [huridocs/uwazi-design#21]
Find existing and current issues for text references in UWAZI

**Comment by aphilop** [comment]
Issues relevant to text references are collected in [a relevant milestone](https://github.com/huridocs/uwazi/milestone/56) and also listed as observations in the [Miro discovery board](https://miro.com/app/board/uXjVKu15oZA=/?moveToWidget=3458764595797658433&cot=14)
