### ISSUE TITLE
Talk with Bono

### ISSUE THREAD

**Issue by juanmnl** [huridocs/uwazi-design#22]
Session planned for Wed Aug 7, 18:00 CET

Questions covered:

- What is your experience (positive, negative) with other tools regarding how they handle creating/organizing/accessing text references?
- If you have used the Uwazi text reference functionality: what is working good, any pain points, suggestions for improvements?
- What expectations would you have from a system that handles text references in an automatic way (if possible)?

**Comment by aphilop** [comment]
Notes from the discussions documented in the relevant[ Miro discovery board](https://miro.com/app/board/uXjVKu15oZA=/?share_link_id=427104692578)
