### ISSUE TITLE
Figure out with which external users we can talk with

### ISSUE THREAD

**Issue by juanmnl** [huridocs/uwazi-design#27]
- [x] Check with PT what partners would be relevant to talk to
        Matel will get us in contact with the IHRDA team
- [x] Create a list of contact persons
       We have two contact persons: one from IHRDA and one from Cecil
- [x] Ask contact persons to participate in the discovery
       We sent both contact persons an email explaining the purpose of our discovery and giving them the option to book a session at a day/time convenient for them
- [x] Set up appointments
       Interview with contact person from Cecil conducted on Wed 11/09 at 14:00 CET
       Interview with contact person from IHRDA planned for Thursday 26/09 at 12:00 CET

**Comment by txau** [comment]
The heaviest current user is IHRDA, we should definitely talk to them. They also use to have the caselaw analyzer, based in CaseBox, that was replaced with Uwazi. It had a very nice approach to CaseLaw citations.
