### ISSUE TITLE
Talk with txau

### ISSUE THREAD

**Issue by juanmnl** [huridocs/uwazi-design#28]
Goals:
- Review discovery findings
- Get further ideas 
- Define scope for feature
- Define next steps

To-do 
- [x] Set up meeting -> Friday, August 23 - 20:00 CET
- [x] Conduct meeting
- [x] Document results

**Comment by aphilop** [comment]
Next steps defined:
- https://github.com/huridocs/uwazi-design/issues/20#issuecomment-2310501030
- https://github.com/orgs/huridocs/projects/2/views/8?pane=issue&itemId=76419113
